Update

diff --git a/.github/workflows/amplify.yml b/.github/workflows/amplify.yml
--- a/.github/workflows/amplify.yml
+++ b/.github/workflows/amplify.yml
@@ -44,34 +44,32 @@ jobs:
           aws amplify create-branch --app-id "$APP_ID" --branch-name "$BRANCH_NAME"
         fi
 
-        - name: Trigger Amplify Deploy
-        env:
-          APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
-          AMPLIFY_DOMAIN: ${{ secrets.AMPLIFY_DOMAIN }}
-        run: |
-          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
-          echo "Triggering deployment for branch: $BRANCH_NAME"
-          
-          # Validar que las variables no estén vacías
-          if [[ -z "$APP_ID" ]]; then
-            echo "Error: APP_ID está vacío. Revisa el secreto AMPLIFY_APP_ID."
-            exit 1
-          fi
-  
-          if [[ -z "$BRANCH_NAME" ]]; then
-            echo "Error: BRANCH_NAME está vacío. Asegúrate de que el evento de PR sea válido."
-            exit 1
-          fi
-  
-          # Intentar crear el deployment
-          DEPLOYMENT_RESPONSE=$(aws amplify create-deployment --app-id "$APP_ID" --branch-name "$BRANCH_NAME" 2>&1) || {
-            echo "Error al crear el despliegue: $DEPLOYMENT_RESPONSE"
-            exit 1
-          }
-  
-          # Extraer la URL del despliegue
-          echo "AMPLIFY_URL=https://${BRANCH_NAME}.${AMPLIFY_DOMAIN}" >> $GITHUB_ENV
-          echo "Deployment triggered for branch: $BRANCH_NAME"
+    - name: Trigger Amplify Deploy
+      env:
+        APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
+        AMPLIFY_DOMAIN: ${{ secrets.AMPLIFY_DOMAIN }}
+      run: |
+        BRANCH_NAME="test"
+        echo "Triggering deployment for branch: $BRANCH_NAME"
+
+        # Validar que las variables no estén vacías
+        if [[ -z "$APP_ID" ]]; then
+          echo "Error: APP_ID está vacío. Revisa el secreto AMPLIFY_APP_ID."
+          exit 1
+        fi
+
+        if [[ -z "$BRANCH_NAME" ]]; then
+          echo "Error: BRANCH_NAME está vacío. Asegúrate de que el evento de PR sea válido."
+          exit 1
+        fi
+
+        DEPLOYMENT_RESPONSE=$(aws amplify create-deployment --app-id "$APP_ID" --branch-name "$BRANCH_NAME" 2>&1) || {
+          echo "Error al crear el despliegue: $DEPLOYMENT_RESPONSE"
+          exit 1
+        }
+
+        echo "AMPLIFY_URL=https://${BRANCH_NAME}.${AMPLIFY_DOMAIN}" >> $GITHUB_ENV
+        echo "Deployment triggered for branch: $BRANCH_NAME"
           
     - name: Wait for Deployment to Complete
       env:
